import moment from 'moment';

import {
    formatThaiDateUi,
    getCreateDateTime
} from '../../utils/DateUtils';

export const soMasterModel = () => {
    return {
        docId: null,
        compId: null,
        docNo: null,
        docDate: formatThaiDateUi(moment()),
        docStatus: parseInt("1", 10),
        docStatusTransport: parseInt("1", 10),
        docStatusReceive: parseInt("1", 10),
        docCode: parseInt("7", 10),
        docType: parseInt("1", 10),
        docFor: parseInt("1", 10),
        docIsPickingList: "N",
        docIsInv: "N",
        refDocID: null,
        refDoc: null,
        refDocDate: null,
        refProjectID: null,
        refProjectNo: null,
        transportType: parseInt("1", 10),
        docRemark1: null,
        docRemark2: null,
        arID: null,
        arCode: null,
        docDueDate: formatThaiDateUi(moment()),
        actionHold: parseInt("0", 10),
        discountValue: parseInt("0", 10),
        discountValueType: null,
        discountValueTotal: parseFloat("0.00"),
        discountCash: parseFloat("0.00"),
        discountCashType: null,
        discountTransport: parseFloat("0.00"),
        discountTransportType: null,
        isVat: null,
        docSEQ: null,
        creditTerm: null,
        creditTerm1Day: parseInt("0", 10),
        creditTerm1Remark: null,
        creditTerm2Remark: null,
        accCode: "0000",
        empName: null,
        createdDate: getCreateDateTime(),
        createdByName: window.localStorage.getItem('name'),
        createdById: window.localStorage.getItem('emp_id'),
        updateDate: null,
        updateByName: null,
        updateById: null,
        approvedDate: null,
        approvedByName: null,
        approvedById: null,
        cancelDate: null,
        cancelByName: null,
        cancelById: null,
        approvedMemo: null,
        printedStatus: "N",
        printedDate: null,
        printedBy: null
    };
};